apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- storage.yaml
- secrets.yaml

commonLabels:
  app: beam-messenger
  version: v1.0.0

namespace: default