apiVersion: v1
kind: Service
metadata:
  name: beam-messenger-service
  labels:
    app: beam-messenger
spec:
  selector:
    app: beam-messenger
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beam-messenger-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: beam-messenger.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: beam-messenger-service
            port:
              number: 80